### PR TITLE
Fix argv issues string param not functional

### PR DESCRIPTION
**Pull request by cgriego**
Work on addressing #2 

We're not sure quite what the vision was supposed to be since the docs and implementation do not match, but here we look at a `string` input if set or fallback to `from`. The `string` can be a mix of any static or dynamic data from the action input and interpolation using the event template.

I also fixed an issue where setNeutral isn't supported with GitHub Actions v2 yet.

### CODE REVIEW

**Comment by ghost** [comment]
@cgriego What's the status on this PR?  I'm trying to using `string`, but facing the same difficulties that are mentioned on #2.

**Comment by cgriego** [comment]
@rjharvey We are successfully using our branch for this pull request in our workflows everyday.

**Comment by allomov** [comment]
@cgriego thank you very much for your fix. it saved me time.

I hope it will be merge soon /cc @AntiFish03

**Comment by jibsonline** [comment]
This is a much needed fix! Any plans to be merged?
@drudzikatlassian

**Comment by rudzon** [comment]
@cgriego Thanks for contribution! 
The mentioned issues should be fixed in latest action release https://github.com/atlassian/gajira-find-issue-key/releases/tag/v2.0.2

**Pull request closed without merging**
